version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/webapp_frontend
hooks:
  BeforeInstall:
    - location: scripts/before-install.sh
      runas: ubuntu
      timeout: 300
  AfterInstall:
    - location: scripts/npm-install.sh
      runas: ubuntu
      timeout: 300